# Generated by Django 4.2.1 on 2023-05-31 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('city', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('CONCERT', 'Concert'), ('CONFERENCE', 'Conference'), ('EXHIBITION', 'Exhibition'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('PARTY', 'Party'), ('EVENT', 'Event')], default='EVENT', max_length=10)),
                ('price_low', models.FloatField(blank=True, null=True)),
                ('price_high', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('language', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary')], max_length=10, null=True)),
                ('events', models.ManyToManyField(related_name='events', to='app.event')),
                ('interests', models.ManyToManyField(related_name='interests', to='app.interest')),
                ('organizer_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_events', to='app.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.event')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='favorite_events', to='app.userprofile'),
        ),
        migrations.AddField(
            model_name='event',
            name='awaiting_invite',
            field=models.ManyToManyField(blank=True, related_name='events_awaiting_invite', to='app.userprofile'),
        ),
    ]
