# Generated by Django 4.2.1 on 2023-06-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
    ]
