# Generated by Django 4.2.1 on 2023-07-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_title_interest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='app.event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests', to='app.interest'),
        ),
    ]
