# Generated by Django 4.2.1 on 2023-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userprofile_events_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='app.interest'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ManyToManyField(to='app.language'),
        ),
    ]
