# Generated by Django 4.2.1 on 2023-07-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_message_event_remove_message_receiver_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.userprofile'),
            preserve_default=False,
        ),
    ]
