# Generated by Django 4.2.1 on 2023-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
    ]
