# Generated by Django 4.2.1 on 2023-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_image_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events', to='app.event'),
        ),
    ]
