# Generated by Django 4.2.1 on 2023-07-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_userprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(default="Cyprus", max_length=500),
            preserve_default=False,
        ),
    ]
